#define	yymaxdepth ParseMapBinutilsmaxdepth
#define	yyparse	ParseMapBinutilsparse
#define	yylex	ParseMapBinutilslex
#define	yyerror	ParseMapBinutilserror
#define	yylval	ParseMapBinutilslval
#define	yychar	ParseMapBinutilschar
#define	yydebug	ParseMapBinutilsdebug
#define	yypact	ParseMapBinutilspact
#define	yyr1	ParseMapBinutilsr1
#define	yyr2	ParseMapBinutilsr2
#define	yydef	ParseMapBinutilsdef
#define	yychk	ParseMapBinutilschk
#define	yypgo	ParseMapBinutilspgo
#define	yyact	ParseMapBinutilsact
#define	yyexca	ParseMapBinutilsexca
#define yyerrflag ParseMapBinutilserrflag
#define yynerrs	ParseMapBinutilsnerrs
#define	yyps	ParseMapBinutilsps
#define	yypv	ParseMapBinutilspv
#define	yys	ParseMapBinutilss
#define	yy_yys	ParseMapBinutilsyys
#define	yystate	ParseMapBinutilsstate
#define	yytmp	ParseMapBinutilstmp
#define	yyv	ParseMapBinutilsv
#define	yy_yyv	ParseMapBinutilsyyv
#define	yyval	ParseMapBinutilsval
#define	yylloc	ParseMapBinutilslloc
#define yyreds	ParseMapBinutilsreds
#define yytoks	ParseMapBinutilstoks
#define yylhs	ParseMapBinutilsyylhs
#define yylen	ParseMapBinutilsyylen
#define yydefred ParseMapBinutilsyydefred
#define yydgoto	ParseMapBinutilsyydgoto
#define yysindex ParseMapBinutilsyysindex
#define yyrindex ParseMapBinutilsyyrindex
#define yygindex ParseMapBinutilsyygindex
#define yytable	 ParseMapBinutilsyytable
#define yycheck	 ParseMapBinutilsyycheck
#define yyname   ParseMapBinutilsyyname
#define yyrule   ParseMapBinutilsyyrule
