#define yymaxdepth LinkerScriptParsermaxdepth
#define yyparse LinkerScriptParserparse
#define yylex LinkerScriptParserlex
#define yyerror LinkerScriptParsererror
#define yylval LinkerScriptParserlval
#define yychar LinkerScriptParserchar
#define yydebug LinkerScriptParserdebug
#define yypact LinkerScriptParserpact
#define yyr1 LinkerScriptParserr1
#define yyr2 LinkerScriptParserr2
#define yydef LinkerScriptParserdef
#define yychk LinkerScriptParserchk
#define yypgo LinkerScriptParserpgo
#define yyact LinkerScriptParseract
#define yyexca LinkerScriptParserexca
#define yyerrflag LinkerScriptParsererrflag
#define yynerrs LinkerScriptParsernerrs
#define yyps LinkerScriptParserps
#define yypv LinkerScriptParserpv
#define yys LinkerScriptParsers
#define yy_yys LinkerScriptParseryys
#define yystate LinkerScriptParserstate
#define yytmp LinkerScriptParsertmp
#define yyv LinkerScriptParserv
#define yy_yyv LinkerScriptParseryyv
#define yyval LinkerScriptParserval
#define yylloc LinkerScriptParserlloc
#define yyreds LinkerScriptParserreds
#define yytoks LinkerScriptParsertoks
#define yylhs LinkerScriptParseryylhs
#define yylen LinkerScriptParseryylen
#define yydefred LinkerScriptParseryydefred
#define yydgoto LinkerScriptParseryydgoto
#define yysindex LinkerScriptParseryysindex
#define yyrindex LinkerScriptParseryyrindex
#define yygindex LinkerScriptParseryygindex
#define yytable LinkerScriptParseryytable
#define yycheck LinkerScriptParseryycheck
#define yyname LinkerScriptParseryyname
#define yyrule LinkerScriptParseryyrule
/* vim: set shiftwidth=2 expandtab cinoptions=p5,t0,(0, foldmethod=marker tw=80 cindent: */
