#define yymaxdepth lparsemaxdepth
#define yyparse lparseparse
#define yylex lparselex
#define yyerror lparseerror
#define yylval lparselval
#define yychar lparsechar
#define yydebug lparsedebug
#define yypact lparsepact
#define yyr1 lparser1
#define yyr2 lparser2
#define yydef lparsedef
#define yychk lparsechk
#define yypgo lparsepgo
#define yyact lparseact
#define yyexca lparseexca
#define yyerrflag lparseerrflag
#define yynerrs lparsenerrs
#define yyps lparseps
#define yypv lparsepv
#define yys lparses
#define yy_yys lparseyys
#define yystate lparsestate
#define yytmp lparsetmp
#define yyv lparsev
#define yy_yyv lparseyyv
#define yyval lparseval
#define yylloc lparselloc
#define yyreds lparsereds
#define yytoks lparsetoks
#define yylhs lparseyylhs
#define yylen lparseyylen
#define yydefred lparseyydefred
#define yydgoto lparseyydgoto
#define yysindex lparseyysindex
#define yyrindex lparseyyrindex
#define yygindex lparseyygindex
#define yytable lparseyytable
#define yycheck lparseyycheck
#define yyname lparseyyname
#define yyrule lparseyyrule
/* vim: set shiftwidth=2 expandtab cinoptions=p5,t0,(0, foldmethod=marker tw=80 cindent: */
