#define	yymaxdepth ParseMapTiLinkermaxdepth
#define	yyparse	ParseMapTiLinkerparse
#define	yylex	ParseMapTiLinkerlex
#define	yyerror	ParseMapTiLinkererror
#define	yylval	ParseMapTiLinkerlval
#define	yychar	ParseMapTiLinkerchar
#define	yydebug	ParseMapTiLinkerdebug
#define	yypact	ParseMapTiLinkerpact
#define	yyr1	ParseMapTiLinkerr1
#define	yyr2	ParseMapTiLinkerr2
#define	yydef	ParseMapTiLinkerdef
#define	yychk	ParseMapTiLinkerchk
#define	yypgo	ParseMapTiLinkerpgo
#define	yyact	ParseMapTiLinkeract
#define	yyexca	ParseMapTiLinkerexca
#define yyerrflag ParseMapTiLinkererrflag
#define yynerrs	ParseMapTiLinkernerrs
#define	yyps	ParseMapTiLinkerps
#define	yypv	ParseMapTiLinkerpv
#define	yys	ParseMapTiLinkers
#define	yy_yys	ParseMapTiLinkeryys
#define	yystate	ParseMapTiLinkerstate
#define	yytmp	ParseMapTiLinkertmp
#define	yyv	ParseMapTiLinkerv
#define	yy_yyv	ParseMapTiLinkeryyv
#define	yyval	ParseMapTiLinkerval
#define	yylloc	ParseMapTiLinkerlloc
#define yyreds	ParseMapTiLinkerreds
#define yytoks	ParseMapTiLinkertoks
#define yylhs	ParseMapTiLinkeryylhs
#define yylen	ParseMapTiLinkeryylen
#define yydefred ParseMapTiLinkeryydefred
#define yydgoto	ParseMapTiLinkeryydgoto
#define yysindex ParseMapTiLinkeryysindex
#define yyrindex ParseMapTiLinkeryyrindex
#define yygindex ParseMapTiLinkeryygindex
#define yytable	 ParseMapTiLinkeryytable
#define yycheck	 ParseMapTiLinkeryycheck
#define yyname   ParseMapTiLinkeryyname
#define yyrule   ParseMapTiLinkeryyrule
