#ifndef DIABLOANOPTARM_ADVANCED_FACTOR_CANONICALIZE_H
#define DIABLOANOPTARM_ADVANCED_FACTOR_CANONICALIZE_H

void Canonicalize(t_cfg *cfg);

#endif /* DIABLOANOPTARM_ADVANCED_FACTOR_CANONICALIZE_H */
