#ifndef DIABLOANOPTARM_ADVANCED_FACTOR_CALLGRAPH_H
#define DIABLOANOPTARM_ADVANCED_FACTOR_CALLGRAPH_H

std::set<t_function *> CfgDontTouchTheseFunctions(t_cfg *cfg);

#endif /* DIABLOANOPTARM_ADVANCED_FACTOR_CALLGRAPH_H */
