#include <diabloalpha.h>

const alpha_opcode alpha_opcode_table[] = {

/*Memorybasedinstructiondescriptions*/
/*{Opcode,fcode,type,name,disassemblyfunction,assemblyinstruction}*/

{0x08,0xDEAD,ALPHA_ITYPE_MEM,"LDA",AlphaDisassembleMem,AlphaAssembleMem},
{0x09,0xDEAD,ALPHA_ITYPE_MEM,"LDAH",AlphaDisassembleMem,AlphaAssembleMem},
{0x0A,0xDEAD,ALPHA_ITYPE_MEM,"LDBU",AlphaDisassembleMem,AlphaAssembleMem},
{0x0C,0xDEAD,ALPHA_ITYPE_MEM,"LDWU",AlphaDisassembleMem,AlphaAssembleMem},
{0x20,0xDEAD,ALPHA_ITYPE_MEM,"LDF",AlphaDisassembleMem,AlphaAssembleMem},
{0x21,0xDEAD,ALPHA_ITYPE_MEM,"LDG",AlphaDisassembleMem,AlphaAssembleMem},
{0x28,0xDEAD,ALPHA_ITYPE_MEM,"LDL",AlphaDisassembleMem,AlphaAssembleMem},
{0x2A,0xDEAD,ALPHA_ITYPE_MEM,"LDL_L",AlphaDisassembleMem,AlphaAssembleMem},
{0x29,0xDEAD,ALPHA_ITYPE_MEM,"LDQ",AlphaDisassembleMem,AlphaAssembleMem},
{0x2B,0xDEAD,ALPHA_ITYPE_MEM,"LDQ_L",AlphaDisassembleMem,AlphaAssembleMem},
{0x0B,0xDEAD,ALPHA_ITYPE_MEM,"LDQ_U",AlphaDisassembleMem,AlphaAssembleMem},
{0x22,0xDEAD,ALPHA_ITYPE_MEM,"LDS",AlphaDisassembleMem,AlphaAssembleMem},
{0x23,0xDEAD,ALPHA_ITYPE_MEM,"LDT",AlphaDisassembleMem,AlphaAssembleMem},
{0x0E,0xDEAD,ALPHA_ITYPE_MEM,"STB",AlphaDisassembleMem,AlphaAssembleMem},
{0x24,0xDEAD,ALPHA_ITYPE_MEM,"STF",AlphaDisassembleMem,AlphaAssembleMem},
{0x25,0xDEAD,ALPHA_ITYPE_MEM,"STG",AlphaDisassembleMem,AlphaAssembleMem},
{0x26,0xDEAD,ALPHA_ITYPE_MEM,"STS",AlphaDisassembleMem,AlphaAssembleMem},
{0x2C,0xDEAD,ALPHA_ITYPE_MEM,"STL",AlphaDisassembleMem,AlphaAssembleMem},
{0x2E,0xDEAD,ALPHA_ITYPE_MEM,"STL_C",AlphaDisassembleMem,AlphaAssembleMem},
{0x2D,0xDEAD,ALPHA_ITYPE_MEM,"STQ",AlphaDisassembleMem,AlphaAssembleMem},
{0x2F,0xDEAD,ALPHA_ITYPE_MEM,"STQ_C",AlphaDisassembleMem,AlphaAssembleMem},
{0x0F,0xDEAD,ALPHA_ITYPE_MEM,"STQ_U",AlphaDisassembleMem,AlphaAssembleMem},
{0x27,0xDEAD,ALPHA_ITYPE_MEM,"STT",AlphaDisassembleMem,AlphaAssembleMem},
{0x0D,0xDEAD,ALPHA_ITYPE_MEM,"STW",AlphaDisassembleMem,AlphaAssembleMem},

/*Branchinstructiondescriptions*/

{0x39,0xDEAD,ALPHA_ITYPE_BR,"BEQ",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x3E,0xDEAD,ALPHA_ITYPE_BR,"BGE",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x3F,0xDEAD,ALPHA_ITYPE_BR,"BGT",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x38,0xDEAD,ALPHA_ITYPE_BR,"BLBC",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x3C,0xDEAD,ALPHA_ITYPE_BR,"BLBS",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x3B,0xDEAD,ALPHA_ITYPE_BR,"BLE",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x3A,0xDEAD,ALPHA_ITYPE_BR,"BLT",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x3D,0xDEAD,ALPHA_ITYPE_BR,"BNE",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x30,0xDEAD,ALPHA_ITYPE_BR,"BR",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x34,0xDEAD,ALPHA_ITYPE_BR,"BSR",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x31,0xDEAD,ALPHA_ITYPE_BR,"FBEQ",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x36,0xDEAD,ALPHA_ITYPE_BR,"FBGE",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x37,0xDEAD,ALPHA_ITYPE_BR,"FBGT",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x33,0xDEAD,ALPHA_ITYPE_BR,"FBLE",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x32,0xDEAD,ALPHA_ITYPE_BR,"FBLT",AlphaDisassembleBranch,AlphaAssembleBranch},
{0x35,0xDEAD,ALPHA_ITYPE_BR,"FBNE",AlphaDisassembleBranch,AlphaAssembleBranch},

/*Floating point instruction descriptions*/
{0x15,0x080,ALPHA_ITYPE_FP,"ADDF",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0A0,ALPHA_ITYPE_FP,"ADDG",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x80,ALPHA_ITYPE_FP,"ADDS",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0A0,ALPHA_ITYPE_FP,"ADDT",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0A5,ALPHA_ITYPE_FP,"CMPGEQ",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0A7,ALPHA_ITYPE_FP,"CMPGLE",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0A6,ALPHA_ITYPE_FP,"CMPGLT",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0A5,ALPHA_ITYPE_FP,"CMPTEQ",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0A7,ALPHA_ITYPE_FP,"CMPTLE",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0A6,ALPHA_ITYPE_FP,"CMPTLT",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0A4,ALPHA_ITYPE_FP,"CMPTUN",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x020,ALPHA_ITYPE_FP,"CPYS",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x022,ALPHA_ITYPE_FP,"CPYSE",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x021,ALPHA_ITYPE_FP,"CPYSN",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x09E,ALPHA_ITYPE_FP,"CVTDG",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0AD,ALPHA_ITYPE_FP,"CVTGD",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0AC,ALPHA_ITYPE_FP,"CVTGF",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0AF,ALPHA_ITYPE_FP,"CVTGQ",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x010,ALPHA_ITYPE_FP,"CVTLQ",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0BC,ALPHA_ITYPE_FP,"CVTQF",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0BE,ALPHA_ITYPE_FP,"CVTQG",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x030,ALPHA_ITYPE_FP,"CVTQL",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0BC,ALPHA_ITYPE_FP,"CVTQS",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0BE,ALPHA_ITYPE_FP,"CVTQT",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x2AC,ALPHA_ITYPE_FP,"CVTST",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0AF,ALPHA_ITYPE_FP,"CVTTQ",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0AC,ALPHA_ITYPE_FP,"CVTTS",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x083,ALPHA_ITYPE_FP,"DIVF",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0A3,ALPHA_ITYPE_FP,"DIVG",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x083,ALPHA_ITYPE_FP,"DIVS",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0A3,ALPHA_ITYPE_FP,"DIVT",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x02A,ALPHA_ITYPE_FP,"FCMOVEQ",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x02D,ALPHA_ITYPE_FP,"FCMOVGE",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x02F,ALPHA_ITYPE_FP,"FCMOVGT",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x02E,ALPHA_ITYPE_FP,"FCMOVLE",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x02C,ALPHA_ITYPE_FP,"FCMOVLT",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x02B,ALPHA_ITYPE_FP,"FCMOVNE",AlphaDisassembleFp,AlphaAssembleFp},
{0x1C,0x78,ALPHA_ITYPE_FP,"FTOIS",AlphaDisassembleFp,AlphaAssembleFp},
{0x1C,0x70,ALPHA_ITYPE_FP,"FTOIT",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x014,ALPHA_ITYPE_FP,"ITOFF",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x004,ALPHA_ITYPE_FP,"ITOFS",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x024,ALPHA_ITYPE_FP,"ITOFT",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x025,ALPHA_ITYPE_FP,"MF_FPCR",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x024,ALPHA_ITYPE_FP,"MT_FPCR",AlphaDisassembleFp,AlphaAssembleFp},
{0x17,0x082,ALPHA_ITYPE_FP,"MULF",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0A2,ALPHA_ITYPE_FP,"MULG",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x082,ALPHA_ITYPE_FP,"MULS",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0A2,ALPHA_ITYPE_FP,"MULT",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x08A,ALPHA_ITYPE_FP,"SQRTF",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x0AA,ALPHA_ITYPE_FP,"SQRTG",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x08B,ALPHA_ITYPE_FP,"SQRTS",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x0AB,ALPHA_ITYPE_FP,"SQRTT",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x081,ALPHA_ITYPE_FP,"SUBF",AlphaDisassembleFp,AlphaAssembleFp},
{0x15,0x0A1,ALPHA_ITYPE_FP,"SUBG",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x081,ALPHA_ITYPE_FP,"SUBS",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0a1,ALPHA_ITYPE_FP,"SUBT",AlphaDisassembleFp,AlphaAssembleFp},

{0x10,0x00,ALPHA_ITYPE_OPR,"ADDL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x20,ALPHA_ITYPE_OPR,"ADDQ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x61,ALPHA_ITYPE_OPR,"AMASK",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x00,ALPHA_ITYPE_OPR,"AND",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x08,ALPHA_ITYPE_OPR,"BIC",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x20,ALPHA_ITYPE_OPR,"BIS",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x24,ALPHA_ITYPE_OPR,"CMOVEQ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x46,ALPHA_ITYPE_OPR,"CMOVGE",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x66,ALPHA_ITYPE_OPR,"CMOVGT",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x16,ALPHA_ITYPE_OPR,"CMOVLBC",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x14,ALPHA_ITYPE_OPR,"CMOVLBS",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x64,ALPHA_ITYPE_OPR,"CMOVLE",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x44,ALPHA_ITYPE_OPR,"CMOVLT",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x26,ALPHA_ITYPE_OPR,"CMOVNE",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x0F,ALPHA_ITYPE_OPR,"CMPBGE",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x2D,ALPHA_ITYPE_OPR,"CMPEQ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x6D,ALPHA_ITYPE_OPR,"CMPLE",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x4D,ALPHA_ITYPE_OPR,"CMPLT",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x3D,ALPHA_ITYPE_OPR,"CMPULE",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x1D,ALPHA_ITYPE_OPR,"CMPULT",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x32,ALPHA_ITYPE_OPR,"CTLZ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x30,ALPHA_ITYPE_OPR,"CTPOP",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x33,ALPHA_ITYPE_OPR,"CTTZ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x48,ALPHA_ITYPE_OPR,"EQV",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x06,ALPHA_ITYPE_OPR,"EXTBL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x6A,ALPHA_ITYPE_OPR,"EXTLH",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x26,ALPHA_ITYPE_OPR,"EXTLL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x7A,ALPHA_ITYPE_OPR,"EXTQH",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x36,ALPHA_ITYPE_OPR,"EXTQL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x5A,ALPHA_ITYPE_OPR,"EXTWH",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x16,ALPHA_ITYPE_OPR,"EXTWL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x6C,ALPHA_ITYPE_OPR,"IMPLVER",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x0B,ALPHA_ITYPE_OPR,"INSBL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x67,ALPHA_ITYPE_OPR,"INSLH",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x2B,ALPHA_ITYPE_OPR,"INSLL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x77,ALPHA_ITYPE_OPR,"INSQH",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x3B,ALPHA_ITYPE_OPR,"INSQL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x57,ALPHA_ITYPE_OPR,"INSWH",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x1B,ALPHA_ITYPE_OPR,"INSWL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x3E,ALPHA_ITYPE_OPR,"MAXSB8",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x3F,ALPHA_ITYPE_OPR,"MAXSW4",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x3C,ALPHA_ITYPE_OPR,"MAXUB8",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x3D,ALPHA_ITYPE_OPR,"MAXUW4",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x38,ALPHA_ITYPE_OPR,"MINSB8",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x39,ALPHA_ITYPE_OPR,"MINSW4",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x3A,ALPHA_ITYPE_OPR,"MINUB8",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x3B,ALPHA_ITYPE_OPR,"MINUW4",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x02,ALPHA_ITYPE_OPR,"MSKBL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x62,ALPHA_ITYPE_OPR,"MSKLH",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x22,ALPHA_ITYPE_OPR,"MSKLL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x72,ALPHA_ITYPE_OPR,"MSKQH",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x32,ALPHA_ITYPE_OPR,"MSKQL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x52,ALPHA_ITYPE_OPR,"MSKWH",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x12,ALPHA_ITYPE_OPR,"MSKWL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x13,0x00,ALPHA_ITYPE_OPR,"MULL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x13,0x20,ALPHA_ITYPE_OPR,"MULQ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x28,ALPHA_ITYPE_OPR,"ORNOT",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x31,ALPHA_ITYPE_OPR,"PERR",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x37,ALPHA_ITYPE_OPR,"PKLB",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x36,ALPHA_ITYPE_OPR,"PKWB",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x02,ALPHA_ITYPE_OPR,"S4ADDL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x22,ALPHA_ITYPE_OPR,"S4ADDQ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x0B,ALPHA_ITYPE_OPR,"S4SUBL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x2B,ALPHA_ITYPE_OPR,"S4SUBQ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x12,ALPHA_ITYPE_OPR,"S8ADDL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x32,ALPHA_ITYPE_OPR,"S8ADDQ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x1B,ALPHA_ITYPE_OPR,"S8SUBL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x3B,ALPHA_ITYPE_OPR,"S8SUBQ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x00,ALPHA_ITYPE_OPR,"SEXTB",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x01,ALPHA_ITYPE_OPR,"SEXTW",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x39,ALPHA_ITYPE_OPR,"SLL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x3C,ALPHA_ITYPE_OPR,"SRA",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x34,ALPHA_ITYPE_OPR,"SRL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x09,ALPHA_ITYPE_OPR,"SUBL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x49,ALPHA_ITYPE_OPR,"SUBL_V",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x29,ALPHA_ITYPE_OPR,"SUBQ",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x10,0x69,ALPHA_ITYPE_OPR,"SUBQ_V",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x13,0x30,ALPHA_ITYPE_OPR,"UMULH",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x35,ALPHA_ITYPE_OPR,"UNPKBL",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x1C,0x34,ALPHA_ITYPE_OPR,"UNPKBW",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x11,0x40,ALPHA_ITYPE_OPR,"XOR",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x30,ALPHA_ITYPE_OPR,"ZAP",AlphaDisassembleOpr,AlphaAssembleOpr},
{0x12,0x31,ALPHA_ITYPE_OPR,"ZAPNOT",AlphaDisassembleOpr,AlphaAssembleOpr},

/*NEW*/
{0x18,0xC000,ALPHA_ITYPE_MFC,"RPCC",AlphaDisassembleMfc,AlphaAssembleMfc},
{0x18,0xE800,ALPHA_ITYPE_MFC,"ECB",AlphaDisassembleMfc,AlphaAssembleMfc},
{0x18,0x0400,ALPHA_ITYPE_MFC,"EXCB",AlphaDisassembleMfc,AlphaAssembleMfc},
{0x18,0x8000,ALPHA_ITYPE_MFC,"FETCH",AlphaDisassembleMfc,AlphaAssembleMfc},
{0x18,0xA000,ALPHA_ITYPE_MFC,"FETCH_M",AlphaDisassembleMfc,AlphaAssembleMfc},
{0x18,0x4000,ALPHA_ITYPE_MFC,"MB",AlphaDisassembleMfc,AlphaAssembleMfc},
{0x18,0x0000,ALPHA_ITYPE_MFC,"TRAPB",AlphaDisassembleMfc,AlphaAssembleMfc},
{0x18,0xF800,ALPHA_ITYPE_MFC,"WH64",AlphaDisassembleMfc,AlphaAssembleMfc},
{0x18,0x4400,ALPHA_ITYPE_MFC,"WMB",AlphaDisassembleMfc,AlphaAssembleMfc},

/* Memory / Branch format instructions */

//{0x34,0xDEAD,ALPHA_ITYPE_MBR,"MBR",AlphaDisassembleMemBranch,	AlphaAssembleMemBranch},

{0x1A,0x00,ALPHA_ITYPE_MBR,"JMP",AlphaDisassembleMemBranch, AlphaAssembleMemBranch},

{0x1A,0x01,ALPHA_ITYPE_MBR,"JSR",AlphaDisassembleMemBranch, AlphaAssembleMemBranch},

{0x1A,0x03,ALPHA_ITYPE_MBR,"JSR_COROUTINE",AlphaDisassembleMemBranch,AlphaAssembleMemBranch},

{0x1A,0x02,ALPHA_ITYPE_MBR,"RET",AlphaDisassembleMemBranch,AlphaAssembleMemBranch},

/*Priveleged PALcode instructions*/

{0x00,0x00,ALPHA_ITYPE_PAL,"PAL_halt",AlphaDisassemblePal,AlphaAssemblePal},

{0x00,0x01,ALPHA_ITYPE_PAL,"PAL_cflush",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x02,ALPHA_ITYPE_PAL,"PAL_draina",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x09,ALPHA_ITYPE_PAL,"PAL_cserve",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x0A,ALPHA_ITYPE_PAL,"PAL_swppal",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x0D,ALPHA_ITYPE_PAL,"PAL_wripir",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x10,ALPHA_ITYPE_PAL,"PAL_rdmces",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x11,ALPHA_ITYPE_PAL,"PAL_wrmces",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x34,ALPHA_ITYPE_PAL,"PAL_wrent",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x39,ALPHA_ITYPE_PAL,"PAL_wrperfmon",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x3E,ALPHA_ITYPE_PAL,"PAL_wtint",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x92,ALPHA_ITYPE_PAL,"PAL_urti",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0xAE,ALPHA_ITYPE_PAL,"PAL_clrfen",AlphaDisassemblePal,AlphaAssemblePal},


/* marker */

/* end marker */

{0x00,0x36,ALPHA_ITYPE_PAL,"PAL_rdps",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x3A,ALPHA_ITYPE_PAL,"PAL_rdusp",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x32,ALPHA_ITYPE_PAL,"PAL_rdval",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x3D,ALPHA_ITYPE_PAL,"PAL_rtsys",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x3F,ALPHA_ITYPE_PAL,"PAL_rti",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x30,ALPHA_ITYPE_PAL,"PAL_swpctx",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x35,ALPHA_ITYPE_PAL,"PAL_swpipl",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x33,ALPHA_ITYPE_PAL,"PAL_tbi",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x3C,ALPHA_ITYPE_PAL,"PAL_whami",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x2B,ALPHA_ITYPE_PAL,"PAL_wrfen",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x37,ALPHA_ITYPE_PAL,"PAL_wrkgp",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x38,ALPHA_ITYPE_PAL,"PAL_wrusp",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x31,ALPHA_ITYPE_PAL,"PAL_wrval",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x2D,ALPHA_ITYPE_PAL,"PAL_wrvptptr",AlphaDisassemblePal,AlphaAssemblePal},

/*Unprivileged PALcode instructions*/

{0x00,0x80,ALPHA_ITYPE_PAL,"PAL_pbt",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x81,ALPHA_ITYPE_PAL,"PAL_bugchk",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x83,ALPHA_ITYPE_PAL,"PAL_callsys",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0xAA,ALPHA_ITYPE_PAL,"PAL_gentrap",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x86,ALPHA_ITYPE_PAL,"PAL_imb",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x9E,ALPHA_ITYPE_PAL,"PAL_rduniq",AlphaDisassemblePal,AlphaAssemblePal},
{0x00,0x9F,ALPHA_ITYPE_PAL,"PAL_wruniq",AlphaDisassemblePal,AlphaAssemblePal},

/* Theres more.... IEEE Floating point instruction extensions */

{0x16,0x000,ALPHA_ITYPE_FP,"ADDS_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x040,ALPHA_ITYPE_FP,"ADDS_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0C0,ALPHA_ITYPE_FP,"ADDS_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x180,ALPHA_ITYPE_FP,"ADDS_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x100,ALPHA_ITYPE_FP,"ADDS_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x140,ALPHA_ITYPE_FP,"ADDS_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1C0,ALPHA_ITYPE_FP,"ADDS_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x580,ALPHA_ITYPE_FP,"ADDS_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x500,ALPHA_ITYPE_FP,"ADDS_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x540,ALPHA_ITYPE_FP,"ADDS_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5C0,ALPHA_ITYPE_FP,"ADDS_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x780,ALPHA_ITYPE_FP,"ADDS_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x700,ALPHA_ITYPE_FP,"ADDS_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x740,ALPHA_ITYPE_FP,"ADDS_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7C0,ALPHA_ITYPE_FP,"ADDS_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x020,ALPHA_ITYPE_FP,"ADDT_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x060,ALPHA_ITYPE_FP,"ADDT_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0E0,ALPHA_ITYPE_FP,"ADDT_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1A0,ALPHA_ITYPE_FP,"ADDT_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x120,ALPHA_ITYPE_FP,"ADDT_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x160,ALPHA_ITYPE_FP,"ADDT_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1E0,ALPHA_ITYPE_FP,"ADDT_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5A0,ALPHA_ITYPE_FP,"ADDT_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x520,ALPHA_ITYPE_FP,"ADDT_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x560,ALPHA_ITYPE_FP,"ADDT_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5E0,ALPHA_ITYPE_FP,"ADDT_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7A0,ALPHA_ITYPE_FP,"ADDT_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x720,ALPHA_ITYPE_FP,"ADDT_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x760,ALPHA_ITYPE_FP,"ADDT_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7E0,ALPHA_ITYPE_FP,"ADDT_SUID",AlphaDisassembleFp,AlphaAssembleFp},


{0x16,0x5A5,ALPHA_ITYPE_FP,"CMPTEQ_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5A7,ALPHA_ITYPE_FP,"CMPTLE_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5A6,ALPHA_ITYPE_FP,"CMPTLT_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5A4,ALPHA_ITYPE_FP,"CMPTUN_SU",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x03C,ALPHA_ITYPE_FP,"CVTQS_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x07C,ALPHA_ITYPE_FP,"CVTQS_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0FC,ALPHA_ITYPE_FP,"CVTQS_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7BC,ALPHA_ITYPE_FP,"CVTQS_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x73C,ALPHA_ITYPE_FP,"CVTQS_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x77C,ALPHA_ITYPE_FP,"CVTQS_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7FC,ALPHA_ITYPE_FP,"CVTQS_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x03E,ALPHA_ITYPE_FP,"CVTQT_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x07E,ALPHA_ITYPE_FP,"CVTQT_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0FE,ALPHA_ITYPE_FP,"CVTQT_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7BE,ALPHA_ITYPE_FP,"CVTQT_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x73E,ALPHA_ITYPE_FP,"CVTQT_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x77E,ALPHA_ITYPE_FP,"CVTQT_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7FE,ALPHA_ITYPE_FP,"CVTQT_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x6AC,ALPHA_ITYPE_FP,"CVTST_S",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x02F,ALPHA_ITYPE_FP,"CVTTQ_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1AF,ALPHA_ITYPE_FP,"CVTTQ_V",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x12F,ALPHA_ITYPE_FP,"CVTTQ_VC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5AF,ALPHA_ITYPE_FP,"CVTTQ_SV",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x52F,ALPHA_ITYPE_FP,"CVTTQ_SVC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7AF,ALPHA_ITYPE_FP,"CVTTQ_SVI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x72F,ALPHA_ITYPE_FP,"CVTTQ_SVIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0EF,ALPHA_ITYPE_FP,"CVTTQ_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1EF,ALPHA_ITYPE_FP,"CVTTQ_VD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5EF,ALPHA_ITYPE_FP,"CVTTQ_SVD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7EF,ALPHA_ITYPE_FP,"CVTTQ_SVID",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x06F,ALPHA_ITYPE_FP,"CVTTQ_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x16F,ALPHA_ITYPE_FP,"CVTTQ_VM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x56F,ALPHA_ITYPE_FP,"CVTTQ_SVM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x76F,ALPHA_ITYPE_FP,"CVTTQ_SVIM",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x02C,ALPHA_ITYPE_FP,"CVTTS_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x06C,ALPHA_ITYPE_FP,"CVTTS_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0EC,ALPHA_ITYPE_FP,"CVTTS_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1AC,ALPHA_ITYPE_FP,"CVTTS_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x12C,ALPHA_ITYPE_FP,"CVTTS_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x16C,ALPHA_ITYPE_FP,"CVTTS_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1EC,ALPHA_ITYPE_FP,"CVTTS_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5AC,ALPHA_ITYPE_FP,"CVTTS_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x52C,ALPHA_ITYPE_FP,"CVTTS_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x56C,ALPHA_ITYPE_FP,"CVTTS_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5EC,ALPHA_ITYPE_FP,"CVTTS_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7AC,ALPHA_ITYPE_FP,"CVTTS_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x72C,ALPHA_ITYPE_FP,"CVTTS_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x76C,ALPHA_ITYPE_FP,"CVTTS_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7EC,ALPHA_ITYPE_FP,"CVTTS_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x003,ALPHA_ITYPE_FP,"DIVS_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x043,ALPHA_ITYPE_FP,"DIVS_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0C3,ALPHA_ITYPE_FP,"DIVS_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x183,ALPHA_ITYPE_FP,"DIVS_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x103,ALPHA_ITYPE_FP,"DIVS_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x143,ALPHA_ITYPE_FP,"DIVS_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1C3,ALPHA_ITYPE_FP,"DIVS_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x583,ALPHA_ITYPE_FP,"DIVS_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x503,ALPHA_ITYPE_FP,"DIVS_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x543,ALPHA_ITYPE_FP,"DIVS_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5C3,ALPHA_ITYPE_FP,"DIVS_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x783,ALPHA_ITYPE_FP,"DIVS_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x703,ALPHA_ITYPE_FP,"DIVS_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x743,ALPHA_ITYPE_FP,"DIVS_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7C3,ALPHA_ITYPE_FP,"DIVS_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x023,ALPHA_ITYPE_FP,"DIVT_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x063,ALPHA_ITYPE_FP,"DIVT_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0E3,ALPHA_ITYPE_FP,"DIVT_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1A3,ALPHA_ITYPE_FP,"DIVT_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x123,ALPHA_ITYPE_FP,"DIVT_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x163,ALPHA_ITYPE_FP,"DIVT_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1E3,ALPHA_ITYPE_FP,"DIVT_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5A3,ALPHA_ITYPE_FP,"DIVT_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x523,ALPHA_ITYPE_FP,"DIVT_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x563,ALPHA_ITYPE_FP,"DIVT_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5E3,ALPHA_ITYPE_FP,"DIVT_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7A3,ALPHA_ITYPE_FP,"DIVT_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x723,ALPHA_ITYPE_FP,"DIVT_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x763,ALPHA_ITYPE_FP,"DIVT_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7E3,ALPHA_ITYPE_FP,"DIVT_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x002,ALPHA_ITYPE_FP,"MULS_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x042,ALPHA_ITYPE_FP,"MULS_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0C2,ALPHA_ITYPE_FP,"MULS_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x182,ALPHA_ITYPE_FP,"MULS_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x102,ALPHA_ITYPE_FP,"MULS_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x142,ALPHA_ITYPE_FP,"MULS_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1C2,ALPHA_ITYPE_FP,"MULS_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x582,ALPHA_ITYPE_FP,"MULS_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x502,ALPHA_ITYPE_FP,"MULS_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x542,ALPHA_ITYPE_FP,"MULS_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5C2,ALPHA_ITYPE_FP,"MULS_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x782,ALPHA_ITYPE_FP,"MULS_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x702,ALPHA_ITYPE_FP,"MULS_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x742,ALPHA_ITYPE_FP,"MULS_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7C2,ALPHA_ITYPE_FP,"MULS_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x022,ALPHA_ITYPE_FP,"MULT_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x062,ALPHA_ITYPE_FP,"MULT_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0E2,ALPHA_ITYPE_FP,"MULT_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1A2,ALPHA_ITYPE_FP,"MULT_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x122,ALPHA_ITYPE_FP,"MULT_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x162,ALPHA_ITYPE_FP,"MULT_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1E2,ALPHA_ITYPE_FP,"MULT_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5A2,ALPHA_ITYPE_FP,"MULT_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x522,ALPHA_ITYPE_FP,"MULT_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x562,ALPHA_ITYPE_FP,"MULT_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5E2,ALPHA_ITYPE_FP,"MULT_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7A2,ALPHA_ITYPE_FP,"MULT_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x722,ALPHA_ITYPE_FP,"MULT_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x762,ALPHA_ITYPE_FP,"MULT_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7E2,ALPHA_ITYPE_FP,"MULT_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x14,0x00B,ALPHA_ITYPE_FP,"SQRTS_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x04B,ALPHA_ITYPE_FP,"SQRTS_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x0CB,ALPHA_ITYPE_FP,"SQRTS_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x18B,ALPHA_ITYPE_FP,"SQRTS_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x10B,ALPHA_ITYPE_FP,"SQRTS_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x14B,ALPHA_ITYPE_FP,"SQRTS_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x1CB,ALPHA_ITYPE_FP,"SQRTS_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x58B,ALPHA_ITYPE_FP,"SQRTS_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x50B,ALPHA_ITYPE_FP,"SQRTS_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x54B,ALPHA_ITYPE_FP,"SQRTS_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x5CB,ALPHA_ITYPE_FP,"SQRTS_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x78B,ALPHA_ITYPE_FP,"SQRTS_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x70B,ALPHA_ITYPE_FP,"SQRTS_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x74B,ALPHA_ITYPE_FP,"SQRTS_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x7CB,ALPHA_ITYPE_FP,"SQRTS_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x14,0x02B,ALPHA_ITYPE_FP,"SQRTT_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x06B,ALPHA_ITYPE_FP,"SQRTT_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x0EB,ALPHA_ITYPE_FP,"SQRTT_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x1AB,ALPHA_ITYPE_FP,"SQRTT_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x12B,ALPHA_ITYPE_FP,"SQRTT_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x16B,ALPHA_ITYPE_FP,"SQRTT_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x1EB,ALPHA_ITYPE_FP,"SQRTT_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x5AB,ALPHA_ITYPE_FP,"SQRTT_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x52B,ALPHA_ITYPE_FP,"SQRTT_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x56B,ALPHA_ITYPE_FP,"SQRTT_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x5EB,ALPHA_ITYPE_FP,"SQRTT_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x7AB,ALPHA_ITYPE_FP,"SQRTT_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x72B,ALPHA_ITYPE_FP,"SQRTT_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x76B,ALPHA_ITYPE_FP,"SQRTT_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x14,0x7EB,ALPHA_ITYPE_FP,"SQRTT_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x001,ALPHA_ITYPE_FP,"SUBS_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x041,ALPHA_ITYPE_FP,"SUBS_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0C1,ALPHA_ITYPE_FP,"SUBS_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x181,ALPHA_ITYPE_FP,"SUBS_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x101,ALPHA_ITYPE_FP,"SUBS_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x141,ALPHA_ITYPE_FP,"SUBS_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1C1,ALPHA_ITYPE_FP,"SUBS_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x581,ALPHA_ITYPE_FP,"SUBS_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x501,ALPHA_ITYPE_FP,"SUBS_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x541,ALPHA_ITYPE_FP,"SUBS_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5C1,ALPHA_ITYPE_FP,"SUBS_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x781,ALPHA_ITYPE_FP,"SUBS_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x701,ALPHA_ITYPE_FP,"SUBS_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x741,ALPHA_ITYPE_FP,"SUBS_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7C1,ALPHA_ITYPE_FP,"SUBS_SUID",AlphaDisassembleFp,AlphaAssembleFp},

{0x16,0x021,ALPHA_ITYPE_FP,"SUBT_C",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x061,ALPHA_ITYPE_FP,"SUBT_M",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x0E1,ALPHA_ITYPE_FP,"SUBT_D",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1A1,ALPHA_ITYPE_FP,"SUBT_U",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x121,ALPHA_ITYPE_FP,"SUBT_UC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x161,ALPHA_ITYPE_FP,"SUBT_UM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x1E1,ALPHA_ITYPE_FP,"SUBT_UD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5A1,ALPHA_ITYPE_FP,"SUBT_SU",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x521,ALPHA_ITYPE_FP,"SUBT_SUC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x561,ALPHA_ITYPE_FP,"SUBT_SUM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x5E1,ALPHA_ITYPE_FP,"SUBT_SUD",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7A1,ALPHA_ITYPE_FP,"SUBT_SUI",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x721,ALPHA_ITYPE_FP,"SUBT_SUIC",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x761,ALPHA_ITYPE_FP,"SUBT_SUIM",AlphaDisassembleFp,AlphaAssembleFp},
{0x16,0x7E1,ALPHA_ITYPE_FP,"SUBT_SUID",AlphaDisassembleFp,AlphaAssembleFp}

};
