/*
 * Copyright (C) 2005 {{{
 *      Ramon Bertran Monfort <rbertran@ac.upc.edu>
 *      Lluis Vilanova <xscript@gmx.net>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * }}}
 *
 * This file is part of the PPC port of Diablo (Diablo is a better
 * link-time optimizer)
 */

#include <diabloppc.h>

/* The opcode table.

   The format of the opcode table is:

   NAME OPCODE MASK DISASSEMBLE-FUNCTION ASSEMBLE-FUNCTION PRINT-STRING

   NAME is the name of the instruction.
   OPCODE is the opcode of the instruction.
   MASK is the opcode mask (to get the OPCODE from 32bits instruction)
   DISASSEMBLE-FUNCTION is the funtion called to disassemble
   ASSEMBLE-FUNCTION is the funtion called to assemble
   PRINT-STRING tells how  the instruction should be printed. 

   The disassembler reads the table in order and prints the first
   instruction which matches, so this table is sorted to put more
   specific instructions before more general instructions.  It is also
   sorted by major opcode.  */


#define TRAP_MEMONICS " { $CT == 16 ? lt : $CT == 20 ? le : $CT == 4 ? eq : $CT == 12\
? ge : $CT == 8 ? gt : $CT == 12 ? nl : $CT == 24 ? ne : $CT == 20 ? ng : $CT == 2 ?\
llt : $CT == 6 ? lle : $CT == 5 ? lge  : $CT == 1 ? lgt : $CT == 5 ? lnl  : $CT == 7\
? lng  : $CT == 31 ? u } " 

#define CONDITIONAL_MEMONICS "" 

#define PRINT_RC " { $PPC_FL_RC ? $$ } "

#define PRINT_OE " { $PPC_FL_OE ? o } "

const t_ppc_opcode_entry _ppc_opcode_table[] = {
  {"tdi",      OP(2),          OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "{td ." TRAP_MEMONICS ". i} $REGA,$IMM < 0 ? -$IMM : $IMM"},
  {"twi",      OP(3),          OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "{tw ." TRAP_MEMONICS ".i} $REGA,$IMM < 0 ? -$IMM : $IMM"},
  {"mulli",    OP(7),          OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "$IMM < 0 ? mulli $REGT,$REGA,-$IMM : mulli $REGT,$REGA,$IMM"},
  {"subfic",   OP(8),          OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "subfic $REGT,$REGA,$IMM < 0 ? -$IMM : $IMM"},
  {"cmpli",    OP(10),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "{cmpl . $REGB == 1 ? d : w . i}  $REGT == 0 ? $REGA,$IMM : $REGT,$REGA,$IMM"},
  {"cmpi",     OP(11),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "{cmp . $REGB == 1 ? d : w . i}  $REGT == 0 ? $REGA,$IMM : $REGT,$REGA,$IMM"},
  {"addic",    OP(12),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "$IMM < 0 ? subic $REGT,$REGA,-$IMM : addic $REGT,$REGA,$IMM"},
  {"addic.",   OP(13),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "$IMM < 0 ? subic . $$  $REGT,$REGA,-$IMM : addic . $$  $REGT,$REGA,$IMM"},
  {"addi",     OP(14),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "$REGA == 0 ? li $REGT,$IMM : $IMM < 0 ? subi $REGT,$REGA,-$IMM : addi  $REGT,$REGA,$IMM"},
  {"addis",    OP(15),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "$REGA == 0 ? lis $REGT,$IMM : $IMM < 0 ? subis $REGT,$REGA,$IMM : addis $REGT,$REGA,$IMM"},
  {"bc",       OP(16),         OP_MASK,        PpcDisassembleB,
    PpcAssembleB,                    "$BCOND.$ADDR"},
  {"sc",       SC(17),         SC_MASK,        PpcDisassembleSC,               PpcAssembleSC,                   "sc"},
  {"b",        OP(18),         OP_MASK,        PpcDisassembleI,
    PpcAssembleI,                    "{b . $PPC_FL_LINK ? l . $PPC_FL_ABSOLUTE ? a} $ADDR"},
  {"mcrf",     XL(19,0),       XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "mcrf $REGT,$REGA"},
  {"bclr",     XL(19,16),      XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "$BCONDLR"},
  {"rfid",     XL(19,18),      XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "rfid"},
  {"crnor",    XL(19,33),      XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "$REGA==$REGB ? crnot $BITT,$BITA : crnor $BITT,$BITA,$BITB"},
  {"crandc",   XL(19,129),     XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "crandc $BITT,$BITA,$BITB"},
  {"isync",    XL(19,150),     XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "isync"},
  {"crxor",    XL(19,193),     XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "$REGT == $REGA AND $REGA == $REGB ? crclr $BITT : crxor $BITT,$BITA,$BITB"},
  {"crnand",   XL(19,225),     XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "crnand $BITT,$BITA,$BITB"},
  {"crand",    XL(19,257),     XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "crand $BITT,$BITA,$BITB"},
  {"creqv",    XL(19,289),     XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "$REGT == $REGA AND $REGA == $REGB ? crset $BITT : creqv $BITT,$BITA,$BITB"},
  {"crorc",    XL(19,417),     XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "crorc $BITT,$BITA,$BITB"},
  {"cror",     XL(19,449),     XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "$REGA == $REGB ? crmove $REGT, $REGA : cror $BITT,$BITA,$BITB"},
  {"bcctr",    XL(19,528),     XL_MASK,        PpcDisassembleXL,
    PpcAssembleXL,                   "$BCONDCTR"},
  {"rlwimi",   OP(20),         OP_MASK,        PpcDisassembleM,
    PpcAssembleM,                    "$RLEFT"},
  {"rlwinm",   OP(21),         OP_MASK,        PpcDisassembleM,
    PpcAssembleM,                    "$RLEFT"},
  {"rlwnm",    OP(23),         OP_MASK,        PpcDisassembleM,
    PpcAssembleM,                    "$RLEFT"},
  {"ori",      OP(24),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    " $REGT == 0 AND $REGA == 0 AND $IMM == 0 ? nop : ori $REGT,$REGA,$IMM"},
  {"oris",     OP(25),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "oris $REGT,$REGA,$IMM"},
  {"xori",     OP(26),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "xori $REGT,$REGA,$IMM"},
  {"xoris",    OP(27),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "xoris $REGT,$REGA,$IMM"},
  {"andi.",    OP(28),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "andi . $$ $REGT,$REGA,$IMM"},
  {"andis.",   OP(29),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "andis . $$ $REGT,$REGA,$IMM"},
  {"rldicl",   MD(30,0),       MD_MASK,        PpcDisassembleMD,        
    PpcAssembleMD,                   "$RLEFT"},
  {"rldicr",   MD(30,1),       MD_MASK,        PpcDisassembleMD, 
    PpcAssembleMD,                   "$RLEFT"},
  {"rldic",    MD(30,2),       MD_MASK,        PpcDisassembleMD,        
    PpcAssembleMD,                   "$RLEFT"},
  {"rldimi",   MD(30,3),       MD_MASK,        PpcDisassembleMD,        
    PpcAssembleMD,                   "$RLEFT"},
  {"rldcl",    MDS(30,8),      MDS_MASK,       PpcDisassembleMDS, 
    PpcAssembleMDS,                  "$RLEFT"},
  {"rldcr",    MDS(30,9),      MDS_MASK,       PpcDisassembleMDS,
    PpcAssembleMDS,                  "$RLEFT"},
  {"cmp",      X(31,0),        X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "cmp . {$PPC_FL_L ? d : w } $REGT,$REGA,$REGB"},
  {"tw",       X(31,4),        X_MASK,         PpcDisassembleX, 
    PpcAssembleX,                    "{{$CT == 31} AND {$REGA == 0} AND {$REGB == 0}} ?  trap : {tw ." TRAP_MEMONICS "} $REGA,$REGB"},
  {"subfc",    X(31,8),        XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "subfc . " PRINT_OE " . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"mulhdu",   X(31,9),        XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "mulhdu . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"addc",     X(31,10),       XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "addc . " PRINT_OE " . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"mulhwu",   X(31,11),       XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "mulhwu . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"mfcr",     X(31,19),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mfcr $REGT"},
  {"lwarx",    X(31,20),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lwarx $REGT,$REGA,$REGB"},
  {"ldx",      X(31,21),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "ldx $REGT,$REGA,$REGB"},
  {"lwzx",     X(31,23),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lwzx $REGT,$REGA,$REGB"},
  {"slw",      X(31,24),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "slw . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"cntlzw",   X(31,26),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "cntlzw . " PRINT_RC " $REGT,$REGA"},
  {"sld",      X(31,27),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "sld . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"and",      X(31,28),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "and . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"cmpl",     X(31,32),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "cmpl . {$PPC_FL_L ? d : w } $REGT,$REGA,$REGB"},
  {"subf",     X(31,40),       XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "sub . " PRINT_OE " . " PRINT_RC " $REGT,$REGB,$REGA"},
  {"ldux",     X(31,53),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "ldux $REGT,$REGA,$REGB"},
  {"dcbst",    X(31,54),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "dcbst $REGA,$REGB"},
  {"lwzux",    X(31,55),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lwzux $REGT,$REGA,$REGB"},
  {"cntlzd",   X(31,58),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "cntlzd . " PRINT_RC " $REGT,$REGA"},
  {"andc",     X(31,60),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "andc . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"td",       X(31,68),       X_MASK,         PpcDisassembleX,                PpcAssembleX,                    "{td ." TRAP_MEMONICS " } $REGA,$IMM < 0 ? -$IMM : $IMM"},
  {"mulhd",    X(31,73),       X_MASK,         PpcDisassembleXO,
    PpcAssembleXO,                   "mulhd . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"mulhw",    X(31,75),       X_MASK,         PpcDisassembleXO,
    PpcAssembleXO,                   "mulhw . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"mfmsr",    X(31,83),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mfmsr $REGT"},
  {"ldarx",    X(31,84),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "ldarx $REGT,$REGA,$REGB"},
  {"dcbf",     X(31,86),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "dcbf $REGA,$REGB"},
  {"lbzx",     X(31,87),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lbzx $REGT,$REGA,$REGB"},
  {"neg",      X(31,104),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "neg . " PRINT_OE " . " PRINT_RC " $REGT, $REGA"},
  {"lbzux",    X(31,119),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lbzux $REGT,$REGA,$REGB"},
  {"nor",      X(31,124),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "$REGA == $REGB ? not . " PRINT_RC " $REGT,$REGA : nor . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"subfe",    X(31,136),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "subfe . " PRINT_RC " . " PRINT_OE " $REGT,$REGA,$REGB"},
  {"adde",     X(31,138),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "adde . " PRINT_RC " . " PRINT_OE " $REGT,$REGA,$REGB"},
  {"mtcrf",    X(31,144),      X_MASK,         PpcDisassembleXFX,
    PpcAssembleXFX,                  "mtcrf $MASK,$REGA"},
  {"mtocrf",   X(31,144) | OPC(1, 11, 1), X_MASK | OPC_MASK(11, 1),
    PpcDisassembleXFX, PpcAssembleXFX, "mtocrf $MASK,$REGA"},
  {"mtmsr",    X(31,146),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mtmsr $REGA,$PPC_FL_L"},
  {"stdx",     X(31,149),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stdx $REGA,$REGB,$REGC"},
  {"stwcx.",   X(31,150),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stwcx . $$ $REGA,$REGB,$REGC"},
  {"stwx",     X(31,151),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stwx $REGA,$REGB,$REGC"},
  {"mtmsrd",   X(31,178),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mtmsrd $REGA,$PPC_FL_L"},
  {"stdux",    X(31,181),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stdux $REGA,$REGB,$REGC"},
  {"stwux",    X(31,183),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stwux $REGA,$REGB,$REGC"},
  {"subfze",   X(31,200),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "subfze . " PRINT_OE " . " PRINT_RC " $REGT, $REGA"},
  {"addze",    X(31,202),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "addze . " PRINT_OE " . " PRINT_RC " $REGT,$REGA"},
  {"mtsr",     X(31,210),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mtsr $REGTi,$REGA"},
  {"stdcx.",   X(31,214),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stdcx . $$  $REGA,$REGB,$REGC"},
  {"stbx",     X(31,215),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stbx $REGA,$REGB,$REGC"},
  {"subfme",   X(31,232),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "subfme . " PRINT_OE " . " PRINT_RC " $REGT,$REGA"},
  {"mulld",    X(31,233),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "mulld . " PRINT_OE " . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"addme",    X(31,234),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "addme . " PRINT_OE " . " PRINT_RC " $REGT,$REGA"},
  {"mullw",    X(31,235),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "mullw . " PRINT_OE " . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"mtsrin",   X(31,242),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mtsrin $REGT,$REGA"},
  {"dcbtst",   X(31,246),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "dcbtst $REGA,$REGB"},
  {"stbux",    X(31,247),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stbux $REGA,$REGB,$REGC"},
  {"add",      X(31,266),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "add . " PRINT_OE " . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"dcbt",     X(31,278),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "dcbt $REGA,$REGB"},
  {"lhzx",     X(31,279),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lhzx $REGT,$REGA,$REGB"},
  {"eqv",      X(31,284),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "eqv . " PRINT_RC " $REGA,$REGT,$REGB"},
  {"tlbie",    X(31,306),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "tlbie $REGA,$PPC_FL_L"},
  {"eciwx",    X(31,310),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "eciwx $REGT,$REGA,$REGB"},
  {"lhzux",    X(31,311),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lhzux $REGT,$REGA,$REGB"},
  {"xor",      X(31,316),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "xor . " PRINT_RC " $REGA,$REGT,$REGB"},
  {"mfspr",    X(31,339),      X_MASK,         PpcDisassembleXFX,
    PpcAssembleXFX,                  "$REGAi == $PPC_REG_CTR ? mfctr $REGT : $REGAi == $PPC_REG_LR ? mflr $REGT : $REGAi == $PPC_REG_XER ? mfxer $REGT : mfspr $REGT,$REGA"},
  {"lwax",     X(31,341),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lwax $REGT,$REGA,$REGB"},
  {"lhax",     X(31,343),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lhax $REGT,$REGA,$REGB"},
  {"tlbia",    X(31,370),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "tlbia"},
  {"mftb",     X(31,371),      X_MASK,         PpcDisassembleXFX,
    PpcAssembleXFX,                  "mftb $REGT,$REGA"},
  {"lwaux",    X(31,373),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lwaux $REGT,$REGA,$REGB"},
  {"lhaux",    X(31,375),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lhaux $REGT,$REGA,$REGB"},
  {"slbmte",   X(31,402),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "slbmte $REGA,$REGB"},
  {"sthx",     X(31,407),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "sthx $REGA,$REGB,$REGC"},
  {"orc",      X(31,412),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "orc . " PRINT_RC " $REGA,$REGT,$REGB"},
  {"sradi",    XS(31,413),      XS_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "sradi $REGT,$REGA,$IMM"},
  {"slbie",    X(31,434),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "slbie $REGA"},
  {"ecowx",    X(31,438),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "ecowx $REGT,$REGA,$REGB"},
  {"sthux",    X(31,439),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "sthux $REGA,$REGB,$REGC"},
  {"or",       X(31,444),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "$REGAi == $REGBi ? mr . " PRINT_RC " $REGT,$REGA : or . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"divdu",    X(31,457),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "divdu . " PRINT_OE " . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"divwu",    X(31,459),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "divwu . " PRINT_OE " . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"mtspr",    X(31,467),      X_MASK,         PpcDisassembleXFX,
    PpcAssembleXFX,                  "$REGTi==$PPC_REG_CTR ? mtctr $REGA : $REGTi==$PPC_REG_LR ? mtlr $REGA : $REGTi==$PPC_REG_XER ? mtxer $REGA : mtspr $REGT,$REGA"},
  {"nand",     X(31,476),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "nand . " PRINT_RC " $REGA,$REGT,$REGB"},
  {"divd",     X(31,489),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "divd . " PRINT_OE " . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"divw",     X(31,491),      XO_MASK,        PpcDisassembleXO,
    PpcAssembleXO,                   "divw . " PRINT_OE " . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"slbia",    X(31,498),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "slbia"},
  {"mcrxr",    X(31,512),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mcrxr $REGT"},
  {"lswx",     X(31,533),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lswx $REGT,$REGA,$REGB"},
  {"lwbrx",    X(31,534),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lwbrx $REGT,$REGA,$REGB"},
  {"lfsx",     X(31,535),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lfsx $REGT,$REGA,$REGB"},
  {"srw",      X(31,536),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "srw . " PRINT_RC " $REGA,$REGT,$REGB"},
  {"srd",      X(31,539),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "srd . " PRINT_RC " $REGA,$REGT,$REGB"},
  {"tlbsync",  X(31,566),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "tlbsync"},
  {"lfsux",    X(31,567),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lfsux $REGT,$REGA,$REGB"},
  {"mfsr",     X(31,595),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mfsr $REGT,$REGAi"},
  {"lswi",     X(31,597),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lswi $REGT,$REGA,$REGB"},
  {"sync",     X(31,598),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "sync $PPC_FL_L"},
  {"lfdx",     X(31,599),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lfdx $REGT,$REGA,$REGB"},
  {"lfdux",    X(31,631),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lfdux $REGT,$REGA,$REGB"},
  {"mfsrin",   X(31,659),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mfsrin $REGT,$REGA"},
  {"stswx",    X(31,661),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stswx $REGA,$REGB,$REGC"},
  {"stwbrx",   X(31,662),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stwbrx $REGA,$REGB,$REGC"},
  {"stfsx",    X(31,663),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stfsx $REGA,$REGB,$REGC"},
  {"stfsux",   X(31,695),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stfsux $REGA,$REGB,$REGC"},
  {"stswi",    X(31,725),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stswi $REGB,$REGA,$IMM"},
  {"stfdx",    X(31,727),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stfdx $REGA,$REGB,$REGC"},
  {"stfdux",   X(31,759),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stfdux $REGA,$REGB,$REGC"},
  {"lhbrx",    X(31,790),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "lhbrx $REGT,$REGA,$REGB"},
  {"sraw",     X(31,792),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "sraw . " PRINT_RC " $REGA,$REGT,$REGB"},
  {"srad",     X(31,794),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "srad . " PRINT_RC " $REGA,$REGT,$REGB"},
  {"srawi",    X(31,824),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "srawi $REGT,$REGA,$IMM"},
  {"slbmfev",  X(31,851),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "slbmfev $REGT,$REGA"},
  {"eieio",    X(31,854),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "eieio"},
  {"slbmfee",  X(31,915),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "slbmfee $REGT,$REGA"},
  {"sthbrx",   X(31,918),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "sthbrx $REGA,$REGB,$REGC"},
  {"extsh",    X(31,922),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "extsh ." PRINT_RC " $REGT,$REGA"},
  {"extsb",    X(31,954),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "extsb ." PRINT_RC " $REGT,$REGA"},
  {"icbi",     X(31,982),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "icbi $REGA,$REGB"},
  {"stfiwx",   X(31,983),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "stfiwx $REGA,$REGB,$REGC"},
  {"extsw",    X(31,986),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "extsw ." PRINT_RC " $REGT,$REGA"},
  {"dcbz",     X(31,1014),     X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "dcbz $REGA,$REGB"},
  {"lwz",      OP(32),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lwz $REGT,$IMM($REGA)"},
  {"lwzu",     OP(33),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lwzu $REGT,$IMM($REGA)"},
  {"lbz",      OP(34),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lbz $REGT,$IMM($REGA)"},
  {"lbzu",     OP(35),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lbzu $REGT,$IMM($REGA)"},
  {"stw",      OP(36),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "stw $REGA,$IMM($REGB)"},
  {"stwu",     OP(37),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "stwu $REGA,$IMM($REGB)"},
  {"stb",      OP(38),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "stb $REGA,$IMM($REGB)"},
  {"stbu",     OP(39),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "stbu $REGA,$IMM($REGB)"},
  {"lhz",      OP(40),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lhz $REGT,$IMM($REGA)"},
  {"lhzu",     OP(41),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lhzu $REGT,$IMM($REGA)"},
  {"lha",      OP(42),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lha $REGT,$IMM($REGA)"},
  {"lhau",     OP(43),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lhau $REGT,$IMM($REGA)"},
  {"sth",      OP(44),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "sth $REGA,$IMM($REGB)"},
  {"sthu",     OP(45),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "sthu $REGA,$IMM($REGB)"},
  {"lmw",      OP(46),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lmw $REGT,$IMM($REGA)"},
  {"stmw",     OP(47),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "stmw $REGA,$IMM($REGB)"},
  {"lfs",      OP(48),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lfs $REGT,$IMM($REGA)"},
  {"lfsu",     OP(49),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lfsu $REGT,$IMM($REGA)"},
  {"lfd",      OP(50),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lfd $REGT,$IMM($REGA)"},
  {"lfdu",     OP(51),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lfdu $REGT,$IMM($REGA)"},
  {"stfs",     OP(52),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "stfs $REGA,$IMM($REGB)"},
  {"stfsu",    OP(53),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "stfsu $REGA,$IMM($REGB)"},
  {"stfd",     OP(54),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "stfd $REGA,$IMM($REGB)"},
  {"stfdu",    OP(55),         OP_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "stfdu $REGA,$IMM($REGB)"},
  {"ld",       DSO(58,0),      DS_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "ld $REGT,$IMM($REGA)"},
  {"ldu",      DSO(58,1),      DS_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "ldu $REGT,$IMM($REGA)"},
  {"lwa",      DSO(58,2),      DS_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "lwa $REGT,$IMM($REGA)"},
  {"fdivs",    A(59,18),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fdivs . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"fsubs",    A(59,20),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fsubs ." PRINT_RC " $REGT,$REGA,$REGB"},
  {"fadds",    A(59,21),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fadds ." PRINT_RC " $REGT,$REGA,$REGB"},
  {"fsqrts",   A(59,22),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fsqrts ." PRINT_RC " $REGT,$REGA"},
  {"fres",     A(59,24),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fres ." PRINT_RC " $REGT,$REGA"},
  {"fmuls",    A(59,25),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fmuls ." PRINT_RC " $REGT,$REGA,$REGB"},
  {"fmsubs",   A(59,28),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fmsubs ." PRINT_RC " $REGT,$REGA,$REGC,$REGB"},
  {"fmadds",   A(59,29),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fmadds . " PRINT_RC " $REGT,$REGA,$REGC,$REGB"},
  {"fnmsubs",  A(59,30),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fnmsubs . " PRINT_RC " $REGT,$REGA,$REGC,$REGB"},
  {"fnmadds",  A(59,31),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fnmadds . " PRINT_RC " $REGT,$REGA,$REGC,$REGB "},
  {"std",      DSO(62,0),      DS_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "std $REGA, $IMM($REGB)"},
  {"stdu",     DSO(62,1),      DS_MASK,        PpcDisassembleD,
    PpcAssembleD,                    "stdu $REGA, $IMM($REGB)"},
  {"fcmpu",    X(63,0),        X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fcmpu $REGT,$REGA,$REGB"},
  {"frsp",     X(63,12),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "frsp . " PRINT_RC " $REGT,$REGA"},
  {"fctiw",    X(63,14),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fctiw . " PRINT_RC " $REGT,$REGA"},
  {"fctiwz",   X(63,15),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fctiwz . " PRINT_RC " $REGT,$REGA"},
  {"fdiv",     A(63,18),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fdiv ." PRINT_RC " $REGT,$REGA,$REGB"},
  {"fsub",     A(63,20),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fsub ." PRINT_RC " $REGT,$REGA,$REGB"},
  {"fadd",     A(63,21),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fadd ." PRINT_RC " $REGT,$REGA,$REGB"},
  {"fsqrt",    A(63,22),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fsqrt . " PRINT_RC " $REGT,$REGA"},
  {"fsel",     A(63,23),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fsel . " PRINT_RC " $REGT,$REGA,$REGC,$REGB"},
  {"fmul",     A(63,25),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fmul . " PRINT_RC " $REGT, $REGA,$REGB"},
  {"frsqrte",  A(63,26),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "frsqrtge ." PRINT_RC " $REGT,$REGA"},
  {"fmsub",    A(63,28),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fmsub ." PRINT_RC " $REGT,$REGA,$REGC,REGB"},
  {"fmadd",    A(63,29),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fmadd ." PRINT_RC " $REGT,$REGA,$REGC,$REGB"},
  {"fnmsub",   A(63,30),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fnmsub ." PRINT_RC " $REGT,$REGA,$REGC,$REGB"},
  {"fnmadd",   A(63,31),       A_MASK,         PpcDisassembleA,
    PpcAssembleA,                    "fnmadd ." PRINT_RC " $REGT,$REGA,$REGC,$REGB"},
  {"fcmpo",    X(63,32),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fcmpo $REGT,$REGA,$REGB"},
  {"mtfsb1",   X(63,38),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mtfsb1 . " PRINT_RC " $IMM"},
  {"fneg",     X(63,40),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fneg ." PRINT_RC " $REGT, $REGA"},
  {"mcrfs",    X(63,64),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mcrfs $REGT,$IMM"},
  {"mtfsb0",   X(63,70),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mtfsb0 . " PRINT_RC " $IMM"},
  {"fmr",      X(63,72),       X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fmr ." PRINT_RC " $REGT,$REGA"},
  {"mtfsfi",   X(63,134),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mtfsfi ." PRINT_RC " $REGA,$IMM"},
  {"fnabs",    X(63,136),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fnabs ." PRINT_RC " $REGT,$REGA"},
  {"fabs",     X(63,264),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fabs ." PRINT_RC " $REGT,$REGA"},
  {"mffs",     X(63,583),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "mffs ." PRINT_RC " $REGT"},
  {"mtfsf",    X(63,711),      X_MASK,         PpcDisassembleXFL,
    PpcAssembleXFL,                  "mtfsf ." PRINT_RC " $REGT,$REGA"},
  {"fctid",    X(63,814),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fctid . " PRINT_RC " $REGT,$REGA"},
  {"fctidz",   X(63,815),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fctidz . " PRINT_RC " $REGT,$REGA"},
  {"fcfid",    X(63,846),      X_MASK,         PpcDisassembleX,
    PpcAssembleX,                    "fcfid . " PRINT_RC " $REGT,$REGA"},
#ifdef PPC_ALTIVEC_SUPPORT
  {"vmhaddshs",VXA(4,32),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vmhaddshs $REGT,$REGA,$REGB,$REGC"},
  {"vmhraddshs",VXA(4,33),     VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vmhraddshs $REGT,$REGA,$REGB,$REGC"},
  {"vmladduhm",VXA(4,34),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vmladduhm $REGT,$REGA,$REGB,$REGC"},
  {"vmsumubm", VXA(4,36),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vmsumubm $REGT,$REGA,$REGB,$REGC"},
  {"vmsummbm", VXA(4,37),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vmsummbm $REGT,$REGA,$REGB,$REGC"},
  {"vmsumuhm", VXA(4,38),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vmsumham $REGT,$REGA,$REGB,$REGC"},
  {"vmsumuhs", VXA(4,39),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vmsumshm $REGT,$REGA,$REGB,$REGC"},
  {"vmsumshm", VXA(4,40),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vmsumshs $REGT,$REGA,$REGB,$REGC"},
  {"vmsumshs", VXA(4,41),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vmsumshs $REGT,$REGA,$REGB,$REGC"},
  {"vsel",     VXA(4,42),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vsel $REGT,$REGA,$REGB,$REGA"},
  {"vperm",    VXA(4,43),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vperm $REGT,$REGA,$REGB,$REGA"},
  {"vsldoi",   VXA(4,44),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vsldoi $REGT,$REGA,$REGB,$IMM"},
  {"vmaddfp",  VX(4,46),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmaddfp $REGT,$REGA,$REGC,$REGB"},
  {"vnmsubfp", VXA(4,47),      VXA_MASK,       PpcDisassembleAltivecVXA,
    PpcAssembleAltivecVXA,           "vnmsubfp $REGT,$REGA,$REGC,$REGB"},
  {"vaddubm",  VX(4,0),        VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vaddubm $REGT,$REGA,$REGB"},
  {"vadduhm",  VX(4,64),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vadduhm $REGT,$REGA,$REGB"},
  {"vadduwm",  VX(4,128),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vadduwm $REGT,$REGA,$REGB"},
  {"vaddcuw",  VX(4,384),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vaddcuw $REGT,$REGA,$REGB"},
  {"vaddubs",  VX(4,512),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vaddubs $REGT,$REGA,$REGB"},
  {"vadduhs",  VX(4,576),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vadduhs $REGT,$REGA,$REGB"},
  {"vadduws",  VX(4,640),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vadduws $REGT,$REGA,$REGB"},
  {"vaddsbs",  VX(4,768),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vaddsbs $REGT,$REGA,$REGB"},
  {"vaddshs",  VX(4,832),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vaddshs $REGT,$REGA,$REGB"},
  {"vaddsws",  VX(4,896),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vaddsws $REGT,$REGA,$REGB"},
  {"vsububm",  VX(4,1024),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsububm $REGT,$REGA,$REGB"},
  {"vsubuhm",  VX(4,1088),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsubuhm $REGT,$REGA,$REGB"},
  {"vsubuwm",  VX(4,1152),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsubuwm $REGT,$REGA,$REGB"},
  {"vsubcuw",  VX(4,1408),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsubcuw $REGT,$REGA,$REGB"},
  {"vsububs",  VX(4,1536),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsububs $REGT,$REGA,$REGB"},
  {"vsubuhs",  VX(4,1600),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsubuhs $REGT,$REGA,$REGB"},
  {"vsubuws",  VX(4,1664),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsubuws $REGT,$REGA,$REGB"},
  {"vsubsbs",  VX(4,1792),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsubsbs $REGT,$REGA,$REGB"},
  {"vsubshs",  VX(4,1856),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsubshs $REGT,$REGA,$REGB"},
  {"vsubsws",  VX(4,1920),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsubsws $REGT,$REGA,$REGB"},
  {"vmaxub",   VX(4,2),        VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmaxub $REGT,$REGA,$REGB"},
  {"vmaxuh",   VX(4,66),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmaxuh $REGT,$REGA,$REGB"},
  {"vmaxuw",   VX(4,130),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmaxuw $REGT,$REGA,$REGB"},
  {"vmaxsb",   VX(4,258),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmaxsb $REGT,$REGA,$REGB"},
  {"vmaxsh",   VX(4,322),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmaxsh $REGT,$REGA,$REGB"},
  {"vmaxsw",   VX(4,386),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmaxsw $REGT,$REGA,$REGB"},
  {"vminub",   VX(4,514),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vminub $REGT,$REGA,$REGB"},
  {"vminuh",   VX(4,578),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vminuh $REGT,$REGA,$REGB"},
  {"vminuw",   VX(4,642),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vminuw $REGT,$REGA,$REGB"},
  {"vminsb",   VX(4,770),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vminsb $REGT,$REGA,$REGB"},
  {"vminsh",   VX(4,834),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vminsh $REGT,$REGA,$REGB"},
  {"vminsw",   VX(4,898),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vminsw $REGT,$REGA,$REGB"},
  {"vavgub",   VX(4,1026),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vavgub $REGT,$REGA,$REGB"},
  {"vavguh",   VX(4,1090),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vavguh $REGT,$REGA,$REGB"},
  {"vavguw",   VX(4,1154),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vavguw $REGT,$REGA,$REGB"},
  {"vavgsb",   VX(4,1282),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vavgsb $REGT,$REGA,$REGB"},
  {"vavgsh",   VX(4,1346),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vavgsh $REGT,$REGA,$REGB"},
  {"vavgsw",   VX(4,1410),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vavgsw $REGT,$REGA,$REGB"},
  {"vrlb",     VX(4,4),        VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vrlb $REGT,$REGA,$REGB"},
  {"vrlh",     VX(4,68),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vrlh $REGT,$REGA,$REGB"},
  {"vrlw",     VX(4,132),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vrlw $REGT,$REGA,$REGB"},
  {"vslb",     VX(4,260),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vslb $REGT,$REGA,$REGB"},
  {"vslh",     VX(4,324),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vslh $REGT,$REGA,$REGB"},
  {"vslw",     VX(4,388),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vslw $REGT,$REGA,$REGB"},
  {"vsl",      VX(4,452),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsl $REGT,$REGA,$REGB"},
  {"vsrb",     VX(4,516),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsrb $REGT,$REGA,$REGB"},
  {"vsrh",     VX(4,580),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsrh $REGT,$REGA,$REGB"},
  {"vsrw",     VX(4,644),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsrw $REGT,$REGA,$REGB"},
  {"vsr",      VX(4,708),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsr $REGT,$REGA,$REGB"},
  {"vsrab",    VX(4,772),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsrab $REGT,$REGA,$REGB"},
  {"vsrah",    VX(4,836),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsrah $REGT,$REGA,$REGB"},
  {"vsraw",    VX(4,900),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsraw $REGT,$REGA,$REGB"},
  {"vand",     VX(4,1028),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vand $REGT,$REGA,$REGB"},
  {"vandc",    VX(4,1092),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vandc $REGT,$REGA,$REGB"},
  {"vor",      VX(4,1156),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vor $REGT,$REGA,$REGB"},
  {"vxor",     VX(4,1220),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vxor $REGT,$REGA,$REGB"},
  {"vnor",     VX(4,1284),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vnor $REGT,$REGA,$REGB"},
  {"mfvscr",   VX(4,1540),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "mfvscr $REGT"},
  {"mtvscr",   VX(4,1604),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "mtvscr $REGA"},
  {"vcmpequb", VXR(4,6),       VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpequb . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpequh", VXR(4,70),      VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpequh . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpequw", VXR(4,134),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpequw . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpeqfp", VXR(4,198),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpeqfp . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpgefp", VXR(4,454),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpgefp . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpgtub", VXR(4,518),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpgtub . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpgtuh", VXR(4,582),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpgtuh . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpgtuw", VXR(4,646),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpegtuw . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpgtfp", VXR(4,710),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpgtfp . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpgtsb", VXR(4,774),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpgtsb . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpgtsh", VXR(4,838),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpgtsh . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpgtsw", VXR(4,902),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpgtsw . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vcmpbfp",  VXR(4,966),     VXR_MASK,       PpcDisassembleAltivecVXR,
    PpcAssembleAltivecVXR,           "vcmpebfp . " PRINT_RC " $REGT,$REGA,$REGB"},
  {"vmuloub",  VX(4,8),        VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmuloub $REGT,$REGA,$REGB"},
  {"vmulouh",  VX(4,72),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmulouh $REGT,$REGA,$REGB"},
  {"vmulosb",  VX(4,264),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmulosb $REGT,$REGA,$REGB"},
  {"vmulosh",  VX(4,328),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmulosh $REGT,$REGA,$REGB"},
  {"vmuleub",  VX(4,520),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmuleub $REGT,$REGA,$REGB"},
  {"vmuleuh",  VX(4,584),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmuleuh $REGT,$REGA,$REGB"},
  {"vmulesb",  VX(4,776),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmulesb $REGT,$REGA,$REGB"},
  {"vmulesh",  VX(4,840),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmulesh $REGT,$REGA,$REGB"},
  {"vsum4ubs", VX(4,1544),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsum4ubs $REGT,$REGA,$REGB"},
  {"vsum4sbs", VX(4,1800),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsum4sbs $REGT,$REGA,$REGB"},
  {"vsum4shs", VX(4,1608),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsum4shs $REGT,$REGA,$REGB"},
  {"vsum2sws", VX(4,1672),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsum2sws $REGT,$REGA,$REGB"},
  {"vsumsws",  VX(4,1928),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsumsws $REGT,$REGA,$REGB"},
  {"vaddfp",   VX(4,10),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vaddfp $REGT,$REGA,$REGB"},
  {"vsubfp",   VX(4,74),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsubfp $REGT,$REGA,$REGB"},
  {"vrefp",    VX(4,266),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vrefp $REGT,$REGA"},
  {"vrsqrtefp",VX(4,330),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vrsqrtefp $REGT,$REGA"},
  {"vexptefp", VX(4,394),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vexptefp $REGT,$REGA"},
  {"vlogefp",  VX(4,458),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vlogefp $REGT,$REGA"},
  {"vrfin",    VX(4,522),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vrfin $REGT,$REGA"},
  {"vrfiz",    VX(4,586),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vrfiz $REGT,$REGA"},
  {"vrfip",    VX(4,650),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vrfip $REGT,$REGA"},
  {"vrfim",    VX(4,714),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vrfim $REGT,$REGA"},
  {"vcfux",    VX(4,778),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vcfux $REGT,$REGA,$IMM"},
  {"vcfsx",    VX(4,842),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vcfsx $REGT,$REGA,$IMM"},
  {"vctuxs",   VX(4,906),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vctuxs $REGT,$REGA,$IMM"},
  {"vctsxs",   VX(4,970),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vctsxs $REGT,$REGA,$IMM"},
  {"vmaxfp",   VX(4,1034),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmaxfp $REGT,$REGA"},
  {"vminfp",   VX(4,1098),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vminfp $REGT,$REGA"},
  {"vmrghb",   VX(4,12),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmrghb $REGT,$REGA"},
  {"vmrghh",   VX(4,76),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmrghh $REGT,$REGA"},
  {"vmrghw",   VX(4,140),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmrghw $REGT,$REGA"},
  {"vmrglb",   VX(4,268),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmrglb $REGT,$REGA"},
  {"vmrglh",   VX(4,332),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmrglh $REGT,$REGA"},
  {"vmrglw",   VX(4,396),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vmrglw $REGT,$REGA"},
  {"vspltb",   VX(4,524),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vspltb $REGT,$REGA,$IMM"},
  {"vsplth",   VX(4,588),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsplth $REGT,$REGA,$IMM"},
  {"vspltw",   VX(4,652),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vspltw $REGT,$REGA,$IMM"},
  {"vspltisb", VX(4,780),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vspltisb $REGT,$IMM"},
  {"vspltish", VX(4,844),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vspltish $REGT,$IMM"},
  {"vspltisw", VX(4,908),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vspltisw $REGT,$IMM"},
  {"vslo",     VX(4,1036),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vslo $REGT,$REGA"},
  {"vsro",     VX(4,1100),     VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vsro $REGT,$REGA"},
  {"vpkuhum",  VX(4,14),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vpkuhum $REGT,$REGA,$REGB"},
  {"vpkuwum",  VX(4,78),       VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vpkuwum $REGT,$REGA,$REGB"},
  {"vpkuhus",  VX(4,142),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vpkuhus $REGT,$REGA,$REGB"},
  {"vpkuwus",  VX(4,206),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vpkuwus $REGT,$REGA,$REGB"},
  {"vpkshus",  VX(4,270),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vpkshus $REGT,$REGA,$REGB"},
  {"vpkswus",  VX(4,334),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vpkswus $REGT,$REGA,$REGB"},
  {"vpkshss",  VX(4,398),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vpkshss $REGT,$REGA,$REGB"},
  {"vpkswss",  VX(4,462),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vpkswss $REGT,$REGA,$REGB"},
  {"vupkhsb",  VX(4,526),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vupkhsb $REGT,$REGA"},
  {"vupkhsh",  VX(4,590),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vupkhsh $REGT,$REGA"},
  {"vupklsb",  VX(4,654),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vupklsb $REGT,$REGA"},
  {"vupklsh",  VX(4,718),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vupklsh $REGT,$REGA"},
  {"vpkpx",    VX(4,782),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vpkpx $REGT,$REGA,$REGB"},
  {"vupkhpx",  VX(4,846),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vupkhpx $REGT,$REGA"},
  {"vupklpx",  VX(4,974),      VX_MASK,        PpcDisassembleAltivecVX,
    PpcAssembleAltivecVX,            "vupklpx $REGT,$REGA"},
  {"lvsl",     X(31,6),        X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "lvsl $REGT,$REGA,$REGB"},
  {"lvsr",     X(31,38),       X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "lvsr $REGT,$REGA,$REGB"},
  {"dst",      XDSS(31,342,0), XDSS_MASK,      PpcDisassembleAltivecXDSS,
    PpcAssembleAltivecXDSS,          "dst $REGA,$REGB,$IMM"},
  {"dstt",     XDSS(31,342,1), XDSS_MASK,      PpcDisassembleAltivecXDSS,
    PpcAssembleAltivecXDSS,          "dstt $REGA,$REGB,$IMM"},
  {"dstst",    XDSS(31,374,0), XDSS_MASK,      PpcDisassembleAltivecXDSS,
    PpcAssembleAltivecXDSS,          "dstst $REGA,$REGB,$IMM"},
  {"dststt",   XDSS(31,374,1), XDSS_MASK,      PpcDisassembleAltivecXDSS,
    PpcAssembleAltivecXDSS,          "dststt $REGA,$REGB,$IMM"},
  {"dss",      XDSS(31,822,0), XDSS_MASK,      PpcDisassembleAltivecXDSS,
    PpcAssembleAltivecXDSS,          "dss $IMM"},
  {"dssall",   XDSS(31,822,1), XDSS_MASK,      PpcDisassembleAltivecXDSS,
    PpcAssembleAltivecXDSS,          "dssall $IMM"},
  {"lvebx",    X(31,71),       X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "lvebx $REGT,$REGA,$REGB"},
  {"lvehx",    X(31,39),       X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "lvehx $REGT,$REGA,$REGB"},
  {"lvewx",    X(31,0),        X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "lvewx $REGT,$REGA,$REGB"},
  {"lvx",      X(31,103),      X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "lvx $REGT,$REGA,$REGB"},
  {"lvxl",     X(31,359),      X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "lvxl $REGT,$REGA,$REGB"},
  {"stvebx",   X(31,135),      X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "stvebx $REGA,$REGB,$REGC"},
  {"stvehx",   X(31,167),      X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "stvehx $REGA,$REGB,$REGC"},
  {"stvewx",   X(31,199),      X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "stvewx $REGA,$REGB,$REGC"},
  {"stvx",     X(31,231),      X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "stvx $REGA,$REGB,$REGC"},
  {"stvxl",    X(31,487),      X_MASK,         PpcDisassembleAltivecX,
    PpcAssembleAltivecX,             "stvxl $REGA,$REGB,$REGC"},
  {"ALTIVEC",  OP(4),          OP_MASK,        PpcDisassembleAltivecUnknown,   PpcAssembleAltivecUnknown,       ""},
  {"ALTIVEC",  OP(31),         OP_MASK,        PpcDisassembleAltivecUnknown,   PpcAssembleAltivecUnknown,       ""},
#endif
  {"unknown",  0,              0,              PpcDisassembleUnknown,          PpcAssembleUnknown,              ""},
  {"",         0,              0,              PpcDisassembleData,
    PpcAssembleData,               "$$ . long $ADDR"}
};

const t_ppc_opcode_entry *ppc_opcode_table = _ppc_opcode_table;

/* vim:set sw=2 tw=80 foldmethod=marker expandtab cindent cinoptions=p5,t0,(0: */
