#define	yymaxdepth ConfParsermaxdepth
#define	yyparse	ConfParserparse
#define	yylex	ConfParserlex
#define	yyerror	ConfParsererror
#define	yylval	ConfParserlval
#define	yychar	ConfParserchar
#define	yydebug	ConfParserdebug
#define	yypact	ConfParserpact
#define	yyr1	ConfParserr1
#define	yyr2	ConfParserr2
#define	yydef	ConfParserdef
#define	yychk	ConfParserchk
#define	yypgo	ConfParserpgo
#define	yyact	ConfParseract
#define	yyexca	ConfParserexca
#define yyerrflag ConfParsererrflag
#define yynerrs	ConfParsernerrs
#define	yyps	ConfParserps
#define	yypv	ConfParserpv
#define	yys	ConfParsers
#define	yy_yys	ConfParseryys
#define	yystate	ConfParserstate
#define	yytmp	ConfParsertmp
#define	yyv	ConfParserv
#define	yy_yyv	ConfParseryyv
#define	yyval	ConfParserval
#define	yylloc	ConfParserlloc
#define yyreds	ConfParserreds
#define yytoks	ConfParsertoks
#define yylhs	ConfParseryylhs
#define yylen	ConfParseryylen
#define yydefred ConfParseryydefred
#define yydgoto	ConfParseryydgoto
#define yysindex ConfParseryysindex
#define yyrindex ConfParseryyrindex
#define yygindex ConfParseryygindex
#define yytable	 ConfParseryytable
#define yycheck	 ConfParseryycheck
#define yyname   ConfParseryyname
#define yyrule   ConfParseryyrule
