#define	yymaxdepth DotParsermaxdepth
#define	yyparse	DotParserparse
#define	yylex	DotParserlex
#define	yyerror	DotParsererror
#define	yylval	DotParserlval
#define	yychar	DotParserchar
#define	yydebug	DotParserdebug
#define	yypact	DotParserpact
#define	yyr1	DotParserr1
#define	yyr2	DotParserr2
#define	yydef	DotParserdef
#define	yychk	DotParserchk
#define	yypgo	DotParserpgo
#define	yyact	DotParseract
#define	yyexca	DotParserexca
#define yyerrflag DotParsererrflag
#define yynerrs	DotParsernerrs
#define	yyps	DotParserps
#define	yypv	DotParserpv
#define	yys	DotParsers
#define	yy_yys	DotParseryys
#define	yystate	DotParserstate
#define	yytmp	DotParsertmp
#define	yyv	DotParserv
#define	yy_yyv	DotParseryyv
#define	yyval	DotParserval
#define	yylloc	DotParserlloc
#define yyreds	DotParserreds
#define yytoks	DotParsertoks
#define yylhs	DotParseryylhs
#define yylen	DotParseryylen
#define yydefred DotParseryydefred
#define yydgoto	DotParseryydgoto
#define yysindex DotParseryysindex
#define yyrindex DotParseryyrindex
#define yygindex DotParseryygindex
#define yytable	 DotParseryytable
#define yycheck	 DotParseryycheck
#define yyname   DotParseryyname
#define yyrule   DotParseryyrule
